### ISSUE TITLE
RFGC: NameError: name 'overwrite' is not defined

### ISSUE THREAD

**Issue by jsk389** [tasoc/starclass#11]
@DJArmstrong (So we have a record of the bugs) 

```
Traceback (most recent call last):
  File "run_starclass.py", line 74, in <module>
    stcl.train(features, labels)
  File "starclass/starclass/RFGCClassifier/RF_GC.py", line 211, in train
    self.classifier.som = fc.makeSOM(features1, outfile=os.path.join(self.data_dir, 'som.txt'), overwrite=overwrite)
NameError: name 'overwrite' is not defined
```

**Comment by DJArmstrong** [comment]
Fixed by PR#15
